#spring:
#  datasource:
#    jndi-name: jdbc/LiveDataSourceName # don't share connection infos in public, so use datasources

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    root: ERROR
